### ISSUE TITLE
Can't open GOW

### ISSUE THREAD

**Issue by ThisIsYang1221** [illusion0001/Windows-Game-Patches#25]
Extract the following contents of the release zip into the game folder.

Rename dinput8.dll from folder !ASI_Loader_x64 to winmm.dll and copy to game folder.

GoW.NoTAA.asi

After used this patch,I can't open GOW....

**Comment by Razvy01** [comment]
I have the same problem. The game opens for a little while, the screen stays black and then it crashes. I'm using the latest version of GoW from GOG.

**Comment by illusion0001** [comment]
Fixed in [1.0.141-9099fcd5](https://github.com/illusion0001/Windows-Game-Patches/releases/tag/1.0.141-9099fcd5)
