### ISSUE TITLE
Documentation for ACUnity, APT2, Control patches

### ISSUE THREAD

**Issue by Keith94** [illusion0001/Windows-Game-Patches#31]
Wondering what these patches do, since there doesn't seem to be any documentation in the README.

**Comment by illusion0001** [comment]
Mostly test patches, AC Unity just skips logo and bypass .text protection, APT2 just tests some string hash from the game and Controls attempts to restore dev menu in #23

**Comment by Keith94** [comment]
I see, thanks!
