### ISSUE TITLE
Death Stranding version.dll doesn't create the .ini file for the .asi fix

### ISSUE THREAD

**Issue by dolixec** [illusion0001/Windows-Game-Patches#32]
I own the original edition, not the Director's Cut edition. I ran the game, but when I look in the root folder of the game, I don't see the .ini that should get created after loading the asi, which means the ASI Loader itself isn't loading into the game.

I've used version 1.0.141-9099fcd5 in case it helps.

**Comment by Keith94** [comment]
Did you try [another name](https://github.com/ThirteenAG/Ultimate-ASI-Loader?tab=readme-ov-file#description)?

**Comment by dolixec** [comment]
> Did you try [another name](https://github.com/ThirteenAG/Ultimate-ASI-Loader?tab=readme-ov-file#description)?

Thanks for your help Keith. Managed to make it run with dinput8.dll.

**Comment by Keith94** [comment]
Great! If anyone has the same problem with DC version, let us know here. :)

**Comment by merlinch** [comment]
I have Death Stranding DC Edition. ASI Loader does not load with my GTX 1660 Ti Mobile GPU, I've tried every name file and only d3d12 that result to crashing meanwhile any filename just ignored by the game. any idea?

**Comment by Keith94** [comment]
I don't have the game to check, but you could possibly try [DxWrapper](https://github.com/elishacloud/dxwrapper) instead, which can also load ASI plugins: https://github.com/elishacloud/dxwrapper/wiki/Configuration#plugins

But if that doesn't work, could be the patch doesn't support your version of the game or something.

**Comment by StabVariation** [comment]
I have the same issue, AMD RX 6600 XT. TAA always turns off when i re-open the game.

Tried everything. Especially the instructions on your page with dinput8.dll or version.dll
